---
- name: include vars
  block:
    - name:
      include_vars: consul1.yml
      when: inventory_hostname == "consul1"
    - name:
      include_vars: consul2.yml
      when: inventory_hostname == "consul2"
    - name:
      include_vars: consul3.yml
      when: inventory_hostname == "consul3"
    - name:
      include_vars: db1.yml
      when: inventory_hostname == "db1"
    - name:
      include_vars: db2.yml
      when: inventory_hostname == "db2"

- name: Install unzip
  yum:
    name: unzip
    state: present

- name: Download consul
  get_url:                     
    url: https://releases.hashicorp.com/consul/1.5.3/consul_1.5.3_linux_amd64.zip
    dest: /tmp/consul.zip      

- name: unzip consul   
  unarchive:                   
    src: /tmp/consul.zip       
    dest: /usr/sbin/           
    remote_src: True           
        
- name: Create user for consul
  user:
    name: consul
    shell: /bin/false          
    home: /etc/consul.d        
        
- name: Get consul directories
  file:
    path: "{{ item }}"         
    state: directory           
    owner: consul              
    group: consul              
  with_items:
      - /etc/consul.d          
      - /opt/consul            

- name: Config consul service
  template:                    
    src: consul.service.j2     
    dest: /etc/systemd/system/consul.service

- name: Config Consul
  template:                    
    src: consul.json.j2        
    dest: /etc/consul.d/consul.json 
    owner: consul              
    group: consul              

- name: Start consul
  systemd:
    name: consul
    enabled: yes
    state: started
