---
# tasks file for keepallived
- name: include vars
  block:
  - name: jiralb1
    include_vars: jiralb1.yml
    when: inventory_hostname == "jiralb1"

  - name: jiralb2
    include_vars: jiralb2.yml
    when: inventory_hostname == "jiralb2"

- name: install keepalived
  yum:
    name: keepalived
    state: present

- name: copy keepalived.timer
  copy:
    src: keepalived.timer
    dest: /usr/lib/systemd/system/keepalived.timer

- name: copy keepalived_restart.service
  copy:
    src: keepalived_restart.service
    dest: /usr/lib/systemd/system/keepalived_restart.service

- name: copy keepalived_restart.sh
  copy:
    src: keepalived_restart.sh
    dest: /opt/keepalived_restart.sh
    mode: a+x

- name: copy keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: copy sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf

- name: read sysctl.conf
  shell: sysctl -p

- name: start keepalived_restart.service
  systemd:
    name: keepalived_restart.service
    enabled: yes
    state: started

- name: start keepalived.timer
  systemd:
    name: keepalived.timer
    enabled: yes
    state: started

- name: start keepalived
  systemd:
    name: keepalived
    enabled: yes
    state: started
